const { DataTypes } = require("sequelize");

module.exports = (sequelize) => {
  const Team = sequelize.define(
    "Team",
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        allowNull: false,
        autoIncrement: true,
        unique: true,
      },
      name: {
        type: DataTypes.ENUM(
          "AGS",
          "Alpine",
          "Alfa Romeo",
          "Andrea Moda",
          "Arrows",
          "Aston Martin",
          "ATS",
          "BAR",
          "Benetton",
          "BMW Sauber",
          "Boro",
          "Brabham",
          "Brawn",
          "BRM",
          "Bruno Giacomelli",
          "Caterham",
          "Coloni",
          "Cooper",
          "Courage Compétition",
          "Dallara",
          "DAMS",
          "De Tomaso",
          "Ecurie Maarsbergen",
          "Eifelland",
          "Emeryson",
          "Ensign",
          "EuroBrun",
          "Ferrari",
          "Finotto",
          "Fittipaldi",
          "Force India",
          "Footwork",
          "Forti",
          "Gilby",
          "Gordini",
          "Gunston",
          "Haas",
          "Hesketh",
          "Hill",
          "Hispania",
          "HRT",
          "Jaguar",
          "Jaguar Racing",
          "Joest Racing",
          "Jordan",
          "Kauhsen",
          "Kojima",
          "Kraco",
          "LEC",
          "Leyton House",
          "Ligier",
          "Lola",
          "Lotus",
          "March",
          "Marussia",
          "Matra",
          "McGuire",
          "McLaren",
          "Mercedes",
          "Merzario",
          "Minardi",
          "Modena",
          "Onyx",
          "Osella",
          "Pacific",
          "Penske",
          "Peugeot",
          "Porsche",
          "Prost",
          "RAM",
          "Racing Point",
          "Rahal-Hogan",
          "Rial",
          "Sauber",
          "Scuderia Centro Sud",
          "Scuderia Ferrari",
          "Scuderia Finotto",
          "Scuderia Ugolini",
          "Shadow",
          "Shannon",
          "Simtek",
          "Spirit",
          "Spyker",
          "Stebro",
          "Stewart",
          "Super Aguri",
          "Surtees",
          "Talbot-Lago",
          "Tecno",
          "Theodore",
          "Toleman",
          "Toro Rosso",
          "Truesports",
          "Tyrrell",
          "UDT Laystall",
          "Vanwall",
          "Virgin",
          "Watson",
          "Williams",
          "Wolf",
          "Zakspeed"
        ),
        allowNull: false,
        unique: false,
      },
    },
    { timestamps: false }
  );

  Team.beforeCreate(async (team, options) => {
    try {
      const maxId = await Team.max("id");

      if (!team.id) {
        team.id = maxId ? maxId + 1 : 509;
      }
    } catch (error) {
      console.error("Error al obtener el máximo id:", error);
      throw error;
    }
  });
};
